version: '3.7'
services:
  postgresql_scheduler:
    # Name and tag of image the Dockerfile creates
    image: mccarthysean/ijack:postgresql_scheduler
    env_file: .env
    networks:
      - traefik-public
    deploy:
      restart_policy:
        condition: on-failure

networks:
  # Use the previously created public network "traefik-public", shared with other services
  traefik-public:
    external: true
