version: '3.7'
services:
  postgresql_scheduler:
    # Name and tag of image the Dockerfile creates
    image: postgresql_scheduler:latest
    env_file: .env
    networks:
      - traefik-public
    deploy:
      restart_policy:
        condition: on-failure

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
