
FROM python:3.8-slim-buster

# Install cron for scheduled jobs and procps for "ps" tool to check running procs
RUN apt-get update && \
    apt-get -y --no-install-recommends install git cron nano procps wget

COPY requirements.txt /
RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt

# Copy my preferred .bashrc to /root/ so that it's automatically "sourced" when the container starts
COPY .bashrc /root/
RUN mkdir -p /project/logs