version: '3.7'
services:
  postgresql_scheduler:
    # Name and tag of image the Dockerfile creates
    image: mccarthysean/ijack:postgresql_scheduler
    # this will signal that the connection is alive after 200 seconds,
    # which is less than the time it takes to drop the connection (300 seconds?), thus preventing it from being dropped.
    # https://stackoverflow.com/questions/56289874/postgres-closes-connection-during-query-after-a-few-hundred-seconds-when-using-p
    # https://github.com/moby/moby/issues/31208#issuecomment-303905737
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=30
      - net.ipv4.tcp_keepalive_probes=10
    env_file: .env
    networks:
      - traefik-public
    deploy:
      # Either global (exactly one container per physical node) or
      # replicated (a specified number of containers). The default is replicated
      mode: replicated
      # For stateless applications using "replicated" mode,
      # the total number of replicas to create
      replicas: 1
      # Don't use a restart policy. Let Docker Swarm handle it.
      restart_policy:
        # condition: on-failure
        condition: any
      placement: 
        constraints: 
          # These jobs take some time, and they're not critical,
          # so we don't want them on the manager node.
          - node.role != manager
      resources:
        limits:
          # The container can use up to X% of a single CPU
          cpus: '0.25'
          # The container can use up to X amount of memory (might need lots when reading from the database)
          memory: 2048M
      # labels:
      #   # Enable logging to Grafana Loki with Promtail
      #   logging: promtail
      #   logging_jobname: postgresql_scheduler
    healthcheck:
      test: [ "CMD", "ping", "-c", "1", "google.com" ]
      interval: 6m
      timeout: 5m
      retries: 3

    volumes:
      - type: volume
        source: postgresql_scheduler_logs_prod
        target: /project/logs
        read_only: false
        volume:
          nocopy: true

networks:
  # Use the previously created public network "traefik-public", shared with other services
  traefik-public:
    external: true

volumes:
  postgresql_scheduler_logs_prod: